# Generated by Django 5.2.7 on 2025-11-18 16:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_number",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Vehicle number must be in a valid format, e.g., KL-08-AZ-1234",
                                regex="^[A-Z]{2}[ -]?[0-9]{1,2}[ -]?[A-Z]{1,2}[ -]?[0-9]{1,4}$",
                            )
                        ],
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("Instant", "Instant"), ("Advance", "Advance")],
                        max_length=100,
                    ),
                ),
                ("booking_time", models.DateField(auto_now_add=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Booked", "Booked"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "BOOKING",
            },
        ),
        migrations.CreateModel(
            name="Carwash_type",
            fields=[
                ("carwash_type", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "db_table": "CARWASH_TYPE",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 digits, optionally starting with +91.",
                                regex="^(?:\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for employee pin",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for employee pin",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "driving_license",
                    models.CharField(
                        help_text="Driving License Number", max_length=100
                    ),
                ),
                (
                    "driving_license_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image of the Driving License",
                        null=True,
                        upload_to=" ",
                    ),
                ),
            ],
            options={
                "db_table": "EMPLOYEE",
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Carwash",
            fields=[
                ("carwash_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_by_user",
                        to="parking.booking",
                    ),
                ),
                (
                    "carwash_type",
                    models.ForeignKey(
                        db_column="carwash_type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carwashes",
                        to="parking.carwash_type",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carwashes",
                        to="parking.employee",
                    ),
                ),
            ],
            options={
                "db_table": "CARWASH",
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                (
                    "streetname",
                    models.CharField(
                        help_text="Building or Streetname", max_length=200
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text="Neighbourhood or Area",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        help_text="6-digit PIN code",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pincode must be a 6-digit number and cannot start with 0.",
                                regex="^[1-9]\\d{5}$",
                            )
                        ],
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                        ],
                        help_text="Admin approval status for owner",
                        max_length=20,
                    ),
                ),
                (
                    "verification_document_image",
                    models.ImageField(
                        blank=True,
                        help_text="Scanned copy of verification document",
                        null=True,
                        upload_to="verification_documents/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OWNER",
            },
        ),
        migrations.CreateModel(
            name="P_Lot",
            fields=[
                ("lot_id", models.AutoField(primary_key=True, serialize=False)),
                ("lot_name", models.CharField(max_length=100)),
                (
                    "streetname",
                    models.CharField(
                        help_text="Enter building or street name", max_length=100
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text="Neighbourhood or Area",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        help_text="6-digit PIN code",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pincode must be a 6-digit number and cannot start with 0.",
                                regex="^[1-9]\\d{5}$",
                            )
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for map pin",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for map pin",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("total_slots", models.CharField(max_length=100)),
                (
                    "available_slots",
                    models.BooleanField(
                        default=True,
                        help_text="True if the parking lot has at least one free slot,False if full.",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_owner",
                        to="parking.ownerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "PARKING_LOT",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="lot",
            field=models.ForeignKey(
                db_column="lot_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_in_lot",
                to="parking.p_lot",
            ),
        ),
        migrations.CreateModel(
            name="P_Slot",
            fields=[
                ("slot_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Hatchback", "Hatchback"),
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Three-Wheeler", "Three-Wheeler"),
                            ("Two-Wheeler", "Two-Wheeler"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The hourly rate of specific Slot",
                        max_digits=5,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="True if the slot is free, false if booked",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_space",
                        to="parking.p_lot",
                    ),
                ),
            ],
            options={
                "db_table": "PARKING_SLOT",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                db_column="slot_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_of_slot",
                to="parking.p_slot",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("pay_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("Cash", "Cash"),
                            ("UPI", "QR code"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_in_booking",
                        to="parking.booking",
                    ),
                ),
            ],
            options={
                "db_table": "PAYEMENT",
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_type", models.CharField(max_length=100)),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="booking_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_assigned",
                        to="parking.booking",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="parking.employee",
                    ),
                ),
            ],
            options={
                "db_table": "TASKS",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 digits, optionally starting with +91.",
                                regex="^(?:\\+91)?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Vehicle number must be in a valid format, e.g., KL-08-AZ-1234",
                                regex="^[A-Z]{2}[ -]?[0-9]{1,2}[ -]?[A-Z]{1,2}[ -]?[0-9]{1,4}$",
                            )
                        ],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Hatchback", "Hatchback"),
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Three-Wheeler", "Three-Wheeler"),
                            ("Two-Wheeler", "Two-Wheeler"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auth_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "USER",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("rev_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(default=5)),
                ("review_desc", models.TextField()),
                (
                    "lot",
                    models.ForeignKey(
                        db_column="lot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_of_lot",
                        to="parking.p_lot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="parking.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "REVIEW",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="parking.userprofile",
            ),
        ),
    ]
