# Generated by Django 5.2.7 on 2025-11-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="p_lot",
            name="available_slots",
        ),
        migrations.AlterField(
            model_name="p_lot",
            name="total_slots",
            field=models.IntegerField(max_length=100),
        ),
    ]
