# Generated by Django 5.2.7 on 2025-11-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0002_remove_p_lot_available_slots_alter_p_lot_total_slots"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carwash_type",
            old_name="carwash_type",
            new_name="carwash_type_id",
        ),
        migrations.AlterField(
            model_name="p_slot",
            name="lot",
            field=models.ForeignKey(
                db_column="lot_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="parking.p_lot",
            ),
        ),
    ]
