# Generated by Django 5.2.7 on 2025-11-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_rename_carwash_type_carwash_type_carwash_type_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="owner",
            field=models.ForeignKey(
                db_column="owner_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="parking.ownerprofile",
            ),
            preserve_default=False,
        ),
    ]
