# Generated by Django 5.2.7 on 2025-11-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0004_employee_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_made_by_user",
                to="parking.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="driving_license_image",
            field=models.ImageField(
                blank=True,
                help_text="Image of the Driving License",
                null=True,
                upload_to="employee_licenses",
            ),
        ),
        migrations.AlterField(
            model_name="p_lot",
            name="total_slots",
            field=models.IntegerField(),
        ),
    ]
