# Generated by Django 5.2.7 on 2025-11-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0005_payment_user_alter_employee_driving_license_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="role",
            field=models.CharField(
                choices=[("User", "User"), ("Owner", "Owner"), ("Admin", "Admin")],
                default="User",
                max_length=15,
            ),
        ),
    ]
