# Generated by Django 5.2.7 on 2025-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0006_alter_authuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Booking end time (default 1 hour from start)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Booking start time (auto-set when created)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="booked",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                help_text="Admin approval status for owner",
                max_length=20,
            ),
        ),
    ]
