# Generated by Django 5.2.7 on 2025-11-29 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0009_alter_payment_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwash",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment Verification"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
