# Generated by Django 5.2.7 on 2025-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0011_review_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="p_lot",
            name="lot_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the parking lot card",
                null=True,
                upload_to="lot_images/",
            ),
        ),
        migrations.AlterField(
            model_name="p_slot",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="The hourly rate of specific Slot",
                max_digits=5,
            ),
        ),
    ]
