# Generated by Django 5.2.7 on 2025-12-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0012_p_lot_lot_image_alter_p_slot_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarWashService",
            fields=[
                (
                    "carwash_service_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Name of the car wash service (e.g., Exterior Wash)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="Service type identifier (e.g., exterior, interior, full)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what's included in this service"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for this service",
                        max_digits=8,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=30, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this service currently available for booking?",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend (e.g., 'droplets', 'sparkles')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "CARWASH_SERVICE",
                "ordering": ["service_name"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("slot_booking", "Parking Slot Booking"),
                    ("car_wash", "Car Wash Service"),
                ],
                default="slot_booking",
                help_text="Type of service being paid for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked parking slot booking (optional, for slot bookings)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="parking.booking",
            ),
        ),
        migrations.CreateModel(
            name="CarWashBooking",
            fields=[
                (
                    "carwash_booking_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior Wash"),
                            ("interior", "Interior Wash"),
                            ("full", "Full Service"),
                            ("premium", "Premium Service"),
                        ],
                        default="full",
                        help_text="Type of car wash service",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Booking price",
                        max_digits=8,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Credit Card"),
                            ("Cash", "Cash"),
                            ("UPI", "QR code"),
                        ],
                        help_text="Payment method used",
                        max_length=100,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Payment verification status",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Booking status",
                        max_length=20,
                    ),
                ),
                (
                    "booking_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the booking was created"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the car wash is scheduled",
                        null=True,
                    ),
                ),
                (
                    "completed_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the car wash was completed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or special requests",
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment transaction ID for online payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        db_column="lot_id",
                        help_text="Optional parking lot for car wash",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carwash_bookings",
                        to="parking.p_lot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carwash_bookings",
                        to="parking.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "CARWASH_BOOKING",
                "ordering": ["-booking_time"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="carwash_booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked car wash booking (optional, for car wash bookings)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="parking.carwashbooking",
            ),
        ),
    ]
