# Generated by Django 5.2.7 on 2025-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0013_carwashservice_payment_service_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carwashbooking",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Exterior", "Exterior"),
                    ("Interior Deep Clean", "Interior Deep Clean"),
                    ("Full Service", "Full Service"),
                ],
                default="Full Service",
                help_text="Type of car wash service",
                max_length=50,
            ),
        ),
    ]
