# Generated by Django 5.2.7 on 2025-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0014_alter_carwashbooking_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="driving_license",
            field=models.ImageField(
                blank=True,
                help_text="User driving license image",
                null=True,
                upload_to="user_licenses/",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Booking end time (default 10 minutes from start)",
                null=True,
            ),
        ),
    ]
