# Generated by Django 5.2.7 on 2025-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0015_userprofile_driving_license_alter_booking_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("SUV", "SUV"),
                    ("Three-Wheeler", "Three-Wheeler"),
                    ("Two-Wheeler", "Two-Wheeler"),
                ],
                default="Sedan",
                help_text="Type of vehicle used for this booking",
                max_length=50,
            ),
        ),
    ]
