# Generated by Django 5.2.7 on 2025-12-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0016_booking_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("Multi-Axle", "Multi-Axle"),
                    ("Three-Wheeler", "Three-Wheeler"),
                    ("Two-Wheeler", "Two-Wheeler"),
                ],
                default="Sedan",
                help_text="Type of vehicle used for this booking",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_column="owner_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="parking.ownerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="p_slot",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("Multi-Axle", "Multi-Axle"),
                    ("Three-Wheeler", "Three-Wheeler"),
                    ("Two-Wheeler", "Two-Wheeler"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Hatchback", "Hatchback"),
                    ("Sedan", "Sedan"),
                    ("Multi-Axle", "Multi-Axle"),
                    ("Three-Wheeler", "Three-Wheeler"),
                    ("Two-Wheeler", "Two-Wheeler"),
                ],
                max_length=50,
            ),
        ),
    ]
