# Generated by Django 5.2.7 on 2025-12-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0017_alter_booking_vehicle_type_alter_employee_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("offline", "Offline"),
                ],
                default="available",
                help_text="Employee availability status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="current_assignments",
            field=models.IntegerField(
                default=0, help_text="Number of active car wash assignments"
            ),
        ),
    ]
