# Generated by Django 5.2.7 on 2025-12-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0018_employee_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwashbooking",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_column="employee_id",
                help_text="Employee assigned to this car wash",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carwash_assignments",
                to="parking.employee",
            ),
        ),
    ]
