# Generated by Django 5.2.7 on 2025-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0019_carwashbooking_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="p_lot",
            name="provides_carwash",
            field=models.BooleanField(
                default=False,
                help_text="True if this parking lot provides car wash services",
            ),
        ),
    ]
