# Generated by Django 5.2.7 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0020_p_lot_provides_carwash"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="carwash",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["active", "pending"])),
                fields=("booking",),
                name="unique_active_carwash_per_booking",
            ),
        ),
    ]
