# Generated by Django 5.2.7 on 2025-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0021_add_unique_active_carwash_constraint"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="carwash",
            name="unique_active_carwash_per_booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["active", "pending"])),
                fields=("booking",),
                name="unique_active_carwash_per_booking",
                violation_error_message="Only one active or pending car wash service is allowed per booking.",
            ),
        ),
    ]
