# Generated by Django 5.2.7 on 2025-12-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0022_add_unique_carwash_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[("SLOT", "Slot Booking"), ("CARWASH", "Carwash Service")],
                default="SLOT",
                help_text="Type of service being reviewed",
                max_length=20,
            ),
        ),
    ]
