# Generated by Django 5.2.7 on 2025-12-05 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0023_add_review_type_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="vehicle_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle number for this specific booking (can differ from user's default)",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Vehicle number must be in a valid format, e.g., KL-08-AZ-1234",
                        regex="^[A-Z]{2}[ -]?[0-9]{1,2}[ -]?[A-Z]{1,2}[ -]?[0-9]{1,4}$",
                    )
                ],
            ),
        ),
    ]
