# Generated by Django 5.2.7 on 2025-12-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0024_make_booking_vehicle_number_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="provides_carwash",
            field=models.BooleanField(
                default=False,
                help_text="True if owner provides car wash services at any lot",
            ),
        ),
    ]
