# Generated by Django 5.2.7 on 2025-12-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0025_ownerprofile_provides_carwash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carwash",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_column="emp_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carwashes",
                to="parking.employee",
            ),
        ),
    ]
