# Generated by Django 5.2.7 on 2025-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0026_alter_carwash_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_renewal",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a renewal payment (50% discount applied)",
            ),
        ),
    ]
